DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP Table IF EXISTS data;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  email TEXT NOT NULL,
  First_name TEXT NOT NULL,
  Last_name TEXT NOT NULL,
  Age INTEGER
);

CREATE TABLE data(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  places varchar(23)  NOT NULL,
  PEOPLE varchar(100) NOT NULL
)
CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
